elevation_hw:
  verbose: True
  sampling_frequency: 100
  joints:
    elevation:
      can_id: 80     ### Check!
      Potentiometer: True
      Gauge: True
      FSR1: False
      FSR2: False
  
elevation_general:
  is_active: False

elevation_control:
  control_rate: 100
  debug: True
  pid_params:
    P: 1
    I: 0
    D: 0
  position_topic: "/elevation_signal"
  elevation_setpoint_topic: "/elevation_setpoint"
