elevation_hw:
  verbose: False
  sampling_freq: 100
  
elevation_general:
  is_active: True

elevation_control:
  control_rate: 100
  debug: True
  pid_params:
    P: 10
    I: 10
    D: 0
  position_topic: "/elevation_signal"
