obstacle_range: 5 # Critical parameter!!
raytrace_range: 5 # Critical parameter!!

transform_tolerance: 5

# Critical parameter!! TODO
footprint: [[0.4, -0.30], [0.4, 0.3], [-0.4,0.3], [-0.4, -0.3]]

plugins:
   - {name: static_map, type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

observation_sources: laser_scan
laser_scan: {data_type: LaserScan, topic: /scan, sensor_frame: base_laser, marking: true, clearing: true}
track_unknown_space: true
unkown_cost_value: 0.1

