# refer to: http://wiki.ros.org/navigation/Tutorials/RobotSetup

local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.5   # Critical parameter!!
  publish_frequence: 0.5  # Critical parameter!!
  static_map: false       # should be true if you're using a map
  rolling_window: true
  width: 6.00
  height: 6.0
  resolution: 0.05 #0.05

  obstacle_layer:
    observation_sources: laser_scan 
    laser_scan: {data_type: LaserScan, topic: /scan, sensor_frame: base_laser, marking: true, clearing: true}

  # padding is 0.1 by default, making difficult to pass through narrow places
  footprint_padding: 0.05
  inflation_layer:
    inflation_radius: 0.3
    cost_scaling_factor: 0.1
