# Planner selection
# we're using the default values
base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

# Recovery behaviors
conservative_reset_dist: 3.0
recovery_behavior_enabled: false # you might want to change it to true
clearing_rotation_allowed: false # this should always be false
shutdown_costmaps: false

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.2

# Global planner
planner_frequency: 0.5 # we want it small if embedded     # Critical parameter!!
planner_patience: 15.0                                    # Critical parameter!!
NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 0.5 # we want it small if embedded  # Critical parameter!!
controller_patience: 15.0                                 # Critical parameter!!
